### PR TITLE
Fix the defination of EpollEvent for mips64 and mips64le

### PR DESCRIPTION
**Pull request by wanghuaiqing2010**
Signed-off-by: wanghuaiqing <wanghuaiqing@loongson.cn>

### CODE REVIEW

**Comment by wanghuaiqing2010** [comment]
Counld you tell me why all checks have failed?
How can I commit my code?

**Comment by ianlancetaylor** [comment]
Have you signed the Copyright License Agreement as explained in the comment above?

**Comment by wanghuaiqing2010** [comment]
@googlebot I signed it!

**Comment by wanghuaiqing2010** [comment]
@ianlancetaylor Yes, I have signed the Copyright License Agreement.
My google account is wanghuaiqing2010@126.com.
The google mailbox corresponding to this account is wanghuaiqing2017@gmail.com.

**Comment by ianlancetaylor** [comment]
Is that e-mail addressed attached to your GitHub user ID as described at https://help.github.com/articles/setting-your-email-in-git/ ?

**Comment by wanghuaiqing2010** [comment]
@ianlancetaylor Could you tell me that which email I should attach to my github user id？
1. wanghuaiqing2010@126.com
2. wanghuaiqing2017@gmail.com

**Comment by wanghuaiqing2010** [comment]
I have set the email wanghuaiqing2017@gmail.com as my Primary email address.
But It does not work.
Please help me.

**Comment by wanghuaiqing2010** [comment]
@googlebot I signed it!

**Comment by ydcool** [comment]
It seems has been alreay fixed in anther PR? https://github.com/kcolford/sys/pull/49

**Pull request closed without merging**
