### PR TITLE
replace golang.org/x/sys to github.com/golang/sys

### PR DESCRIPTION
**Pull request by datochan**
replace "import golang.org/x/sys" to "import github.com/golang/sys"

### CODE REVIEW

**Comment by ianlancetaylor** [comment]
Note that golang.org/x/sys is correct.  This change is not right.

**Comment by datochan** [comment]
@ianlancetaylor `golang.org` can not be accessed in China because of the network firewall.
The code is managed in github.com, don't import golang.org/x/sys.

😂

**Comment by ianlancetaylor** [comment]
That is https://golang.org/issue/8870.

**Comment by piaofudeyu** [comment]
In China , We have to use VPN to contact with golang.org.... 😂😂😂😂😂😂

**Comment by bradfitz** [comment]
We agree that is sad.

We're trying to make things better (mostly @andybons), but ultimately it is China blocking Go, not Go blocking China, so we can't make any promises that things will get or stay better.

We have nothing concrete to announce yet, but @andybons has plans.

**Pull request closed without merging**
